# Generated by Django 2.1.7 on 2019-03-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190317_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='nickname',
        ),
    ]
