# Generated by Django 2.1.7 on 2019-03-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190319_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='top',
            field=models.IntegerField(choices=[(0, '普通'), (1, '置顶')], default=0, verbose_name='置顶'),
        ),
    ]
